Modifying build script to add com components for test impact collector
microsoft/vstest pull request #1007
Opened 2017-08-18 08:41 UTC by prawalagarwal

For test impact collector to work, the com components have to be present in Extensions/TestImpact folder. This change modifies the build script to achieve that.

2017-08-18 08:41 UTC, msftclas commented
@prawalagarwal,
Thanks for your contribution as a Microsoft full-time employee or intern. You do not need to sign a CLA.
_Thanks,
Microsoft Pull Request Bot_

2017-08-22 08:35 UTC, Faizan2304 commented
We have to update [TestPlatform.csproj](https://github.com/Microsoft/vstest/blob/master/src/package/VSIXProject/TestPlatform.csproj#L102) to include new added com component in TestPlatform.Vsix

2017-08-22 08:38 UTC, Faizan2304 requested changes

2017-08-22 08:38 UTC, Faizan2304 commented on scripts/build.ps1
> +    $testImpactComComponentsDir = Join-Path $extensionsPackageDir "TestImpact"
Who and how will these comcomponent will get consumed ?

2017-08-22 08:46 UTC, prawalagarwal commented on scripts/build.ps1
> +    $testImpactComComponentsDir = Join-Path $extensionsPackageDir "TestImpact"
This is getting consumed by test impact collector. The way collector is implemented today requires us to put com components in Extensions/TestImpact directory

2017-08-22 08:56 UTC, Faizan2304 approved these changes
Please create vsix and do some manually testing.
1) Make sure com component dlls are getting drop properly
2) Test impact is working.

Rest look good to me 👍

2017-08-22 08:58 UTC, harshjain2 requested changes
Holding this PR until we have Test Impact DataCollector related changes in TraceCollector.dll

2017-08-30 10:20 UTC, harshjain2 approved these changes

2017-08-30 10:50 UTC, merged