Adding object model changes and Telemetry optin status
microsoft/vstest pull request #1173
Opened 2017-10-06 14:43 UTC by khilan2goel

2017-10-06 14:44 UTC, khilan2goel commented on test/Microsoft.TestPlatform.AcceptanceTests/TelemetryTests.cs
> -﻿// Copyright (c) Microsoft Corporation. All rights reserved.
Removing it as of now, beacause in EnvironmentVariable logic has been removed. Will raise in next PR

2017-10-09 09:28 UTC, harshjain2 commented
Please share test plan/ scenarios verified.

2017-10-09 09:51 UTC, AbhitejJohn commented
It appears that we are also exposing Filtering to Discovery/Run Tests with Test Cases. If we do not support Filtering for any of these please go ahead and throw a warning or error out.

2017-10-09 18:35 UTC, navin22 commented
@AbhitejJohn Clients can pass it but, is it appropriate to throw error/warning. Is it just enough to document it. As TestPlatformOptions can grow.

2017-10-11 10:10 UTC, navin22 approved these changes

2017-10-11 10:10 UTC, navin22 commented on src/vstest.console/TestPlatformHelpers/TestRequestManager.cs
> +                  MetricsPublisherFactory.GetMetricsPublisher(false, CommandLineOptions.Instance.IsDesignMode))
nit: Good to comment this, why we always pass false. Hence by default testplatform will not publish anything.

2017-10-11 10:45 UTC, harshjain2 approved these changes

2017-10-11 11:31 UTC, AbhitejJohn requested changes

2017-10-11 11:36 UTC, AbhitejJohn approved these changes

2017-10-11 12:32 UTC, khilan2goel commented
Regarding showing warning,  I have created bug Refer: https://github.com/Microsoft/vstest/issues/1189  because same is happening in CLI scenarios as well when we pass /testcasefilter along with /listtests

2017-10-11 12:44 UTC, khilan2goel commented on src/Microsoft.TestPlatform.VsTestConsole.TranslationLayer/DiscoveryEventsHandler.cs
> +    public class DiscoveryEventsHandler : ITestDiscoveryEventsHandler2
Done

2017-10-11 12:44 UTC, khilan2goel commented on test/TranslationLayer.UnitTests/VsTestConsoleRequestSenderTests.cs
> +            this.requestSender.DiscoverTests(new List<string>() { "1.dll" }, null, new TestPlatformOptions(), mockHandler.Object);
Done

2017-10-11 13:12 UTC, singhsarab approved these changes
:shipit:

2017-10-12 07:13 UTC, merged