Test Host Extensibility Framework
microsoft/vstest pull request #507
Opened 2017-02-16 14:50 UTC by mayankbansal018

Added TestHost Manager Interface

2017-02-16 14:50 UTC, msftclas commented
Hi __@mayankbansal018__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <p>
        It looks like you're a Microsoft contributor. If you're full-time or an intern, we DON'T require a Contribution License Agreement. If you are a vendor, please DO sign the electronic Contribution License Agreement. It will take 2 minutes and there's no faxing! https://cla.microsoft.com.
    </p>

TTYL, MSBOT;

2017-02-17 04:21 UTC, harshjain2 commented on src/Microsoft.TestPlatform.Client/TestPlatform.cs
> +            //var testHostManager = this.testHostProviderManager.GetTestHostManagerByRunConfiguration(runconfiguration);
nit : this line of code can be removed.

2017-02-22 02:49 UTC, codito commented
Reviewed 54 of 54 files at r1.
Review status: all files reviewed at latest revision, 23 unresolved discussions.

---

*[src/Microsoft.TestPlatform.Client/TestPlatform.cs, line 32 at r1](https://reviewable.io:443/reviews/microsoft/vstest/507#-KdYbsRUvs9hjtgZxRI-:-KdYbsRVJMZN0ixFptBz:b35zny8) ([raw file](https://github.com/microsoft/vstest/blob/bb3fc2ab5070026cbe5067ee9137f389cff7f6dc/src/Microsoft.TestPlatform.Client/TestPlatform.cs#L32)):*
> ```Smalltalk
>         public TestPlatform() : this(new TestEngine())
>         {
>             this.testHostProviderManager = TestHostProviderManager.Instance;
> ```

Please inject this via ctor. I am not sure how we are going to unit test a static usage.

---

*[src/Microsoft.TestPlatform.Client/TestPlatform.cs, line 69 at r1](https://reviewable.io:443/reviews/microsoft/vstest/507#-KdYbAOxokX6WbTYCvyD-r1-69:-KdYbkLH6KGFwNETRo_M:bjbaex5) ([raw file](https://github.com/microsoft/vstest/blob/bb3fc2ab5070026cbe5067ee9137f389cff7f6dc/src/Microsoft.TestPlatform.Client/TestPlatform.cs#L69)):*
<details><summary><i>Previously, harshjain2 (Harsh Jain) wrote…</i></summary><blockquote>

nit : this line of code can be removed.
</blockquote></details>

Mark it with TODO if this is just the framework and you're staging the actual usage to later PR.

---

*[src/Microsoft.TestPlatform.Client/TestPlatform.cs, line 70 at r1](https://reviewable.io:443/reviews/microsoft/vstest/507#-KdYb_1VydJkDfnuS8E-:-KdYb_1VydJkDfnuS8E0:bqgrwp0) ([raw file](https://github.com/microsoft/vstest/blob/bb3fc2ab5070026cbe5067ee9137f389cff7f6dc/src/Microsoft.TestPlatform.Client/TestPlatform.cs#L70)):*
> ```Smalltalk
>             var runconfiguration = XmlRunSettingsUtilities.GetRunConfigurationNode(discoveryCriteria.RunSettings);
>             //var testHostManager = this.testHostProviderManager.GetTestHostManagerByRunConfiguration(runconfiguration);
>             
> ```

nit: remove trailing space

---

*[src/Microsoft.TestPlatform.Client/TestPlatform.cs, line 72 at r1](https://reviewable.io:443/reviews/microsoft/vstest/507#-KdYbd7aTm1PenY7O-99:-KdYbd7aTm1PenY7O-9A:bqgrwp0) ([raw file](https://github.com/microsoft/vstest/blob/bb3fc2ab5070026cbe5067ee9137f389cff7f6dc/src/Microsoft.TestPlatform.Client/TestPlatform.cs#L72)):*
> ```Smalltalk
>             
>             var testHostManager = this.TestEngine.GetDefaultTestHostManager(runconfiguration);
>             
> ```

nit: remove trailing space

---

*[src/Microsoft.TestPlatform.Common/Friends.cs, line 12 at r1](https://reviewable.io:443/reviews/microsoft/vstest/507#-KdYhtTxaYXegO81iVjh:-KdYhtTxaYXegO81iVji:b6syfxw) ([raw file](https://github.com/microsoft/vstest/blob/bb3fc2ab5070026cbe5067ee9137f389cff7f6dc/src/Microsoft.TestPlatform.Common/Friends.cs#L12)):*
> ```Smalltalk
> [assembly: InternalsVisibleTo("Microsoft.TestPlatform.CommunicationUtilities, PublicKey=002400000480000094000000060200000024000052534131000400000100010007d1fa57c4aed9f0a32e84aa0faefd0de9e8fd6aec8f87fb03766c834c99921eb23be79ad9d5dcc1dd9ad236132102900b723cf980957fc4e177108fc607774f29e8320e92ea05ece4e821c0a5efe8f1645c4c0c93c1ab99285d622caa652c1dfad63d745d6f2de5f17e5eaf0fc4963d261c8a12436518206dc093344d5ad293")]
> [assembly: InternalsVisibleTo("Microsoft.VisualStudio.TestPlatform.Common, PublicKey=002400000480000094000000060200000024000052534131000400000100010007d1fa57c4aed9f0a32e84aa0faefd0de9e8fd6aec8f87fb03766c834c99921eb23be79ad9d5dcc1dd9ad236132102900b723cf980957fc4e177108fc607774f29e8320e92ea05ece4e821c0a5efe8f1645c4c0c93c1ab99285d622caa652c1dfad63d745d6f2de5f17e5eaf0fc4963d261c8a12436518206dc093344d5ad293")]
> [assembly: InternalsVisibleTo("Microsoft.VisualStudio.TestPlatform.Client, PublicKey=002400000480000094000000060200000024000052534131000400000100010007d1fa57c4aed9f0a32e84aa0faefd0de9e8fd6aec8f87fb03766c834c99921eb23be79ad9d5dcc1dd9ad236132102900b723cf980957fc4e177108fc607774f29e8320e92ea05ece4e821c0a5efe8f1645c4c0c93c1ab99285d622caa652c1dfad63d745d6f2de5f17e5eaf0fc4963d261c8a12436518206dc093344d5ad293")]
> ```

Not sure which type requires this. Why not make the type public?

---

*[src/Microsoft.TestPlatform.Common/ExtensionFramework/TestPluginDiscoverer.cs, line 68 at r1](https://reviewable.io:443/reviews/microsoft/vstest/507#-KdYcDFcxsePaMdvqU2p:-KdYcDFdj0A76dOA6NpY:b-1uje5m) ([raw file](https://github.com/microsoft/vstest/blob/bb3fc2ab5070026cbe5067ee9137f389cff7f6dc/src/Microsoft.TestPlatform.Common/ExtensionFramework/TestPluginDiscoverer.cs#L68)):*
> ```Smalltalk
>                 TestSettingsProviders = new Dictionary<string, TestSettingsProviderPluginInformation>(StringComparer.OrdinalIgnoreCase),
>                 TestLoggers = new Dictionary<string, TestLoggerPluginInformation>(StringComparer.OrdinalIgnoreCase),
>                 TestHosts = new Dictionary<string, TestHostPluginInformation>(StringComparer.OrdinalIgnoreCase)
> ```

Is `TestHost` the concept or is it `RuntimeProvider`? My understanding is that it is later since a RuntimeProvider will provide ability to (a) deploy app, (b) instantiate the testhost on target, (c) ack that communication is established

This should probably be `TestRuntimePluginInformation`.

---

*[src/Microsoft.TestPlatform.Common/ExtensionFramework/TestPluginDiscoverer.cs, line 246 at r1](https://reviewable.io:443/reviews/microsoft/vstest/507#-KdYi6F4V69-DcRgl86n:-KdYi6F4V69-DcRgl86o:b-4l5vrx) ([raw file](https://github.com/microsoft/vstest/blob/bb3fc2ab5070026cbe5067ee9137f389cff7f6dc/src/Microsoft.TestPlatform.Common/ExtensionFramework/TestPluginDiscoverer.cs#L246)):*
> ```Smalltalk
>                         this.GetTestExtensionFromType<TestLoggerPluginInformation>(type, typeof(ITestLogger), testLoggers);
>                         this.GetTestExtensionFromType<TestSettingsProviderPluginInformation>(type, typeof(ISettingsProvider), testSettingsProviders);
>                         this.GetTestExtensionFromType<TestHostPluginInformation>(type, typeof(ITestHostProvider), testHosts);
> ```

Do we need tests for this?

---

*[src/Microsoft.TestPlatform.Common/ExtensionFramework/Utilities/TestHostPluginInformation.cs, line 11 at r1](https://reviewable.io:443/reviews/microsoft/vstest/507#-KdYcsuPW6S9sSP1c1DL:-KdYcsuPW6S9sSP1c1DM:bytfxpc) ([raw file](https://github.com/microsoft/vstest/blob/bb3fc2ab5070026cbe5067ee9137f389cff7f6dc/src/Microsoft.TestPlatform.Common/ExtensionFramework/Utilities/TestHostPluginInformation.cs#L11)):*
> ```Smalltalk
>     using System.Reflection;
> 
>     using ObjectModel;
> ```

Fully qualified namespace please.

---

*[src/Microsoft.TestPlatform.Common/Hosting/TestHostExtensionManager.cs, line 4 at r1](https://reviewable.io:443/reviews/microsoft/vstest/507#-KdYeDw7-zyd23P79r2U:-KdYeDw8BL_brGDTCIx7:binxh54) ([raw file](https://github.com/microsoft/vstest/blob/bb3fc2ab5070026cbe5067ee9137f389cff7f6dc/src/Microsoft.TestPlatform.Common/Hosting/TestHostExtensionManager.cs#L4)):*
> ```Smalltalk
> // Licensed under the MIT license. See LICENSE file in the project root for full license information.
> 
> namespace Microsoft.VisualStudio.TestPlatform.Common.Hosting
> ```

We're using different namespaces for same concept? TP.Common.Hosting and OM.Host.

---

*[src/Microsoft.TestPlatform.Common/Hosting/TestHostMetadata.cs, line 14 at r1](https://reviewable.io:443/reviews/microsoft/vstest/507#-KdYeWwgBobC7IyB_5sP:-KdYeWwgBobC7IyB_5sQ:bqvva8r) ([raw file](https://github.com/microsoft/vstest/blob/bb3fc2ab5070026cbe5067ee9137f389cff7f6dc/src/Microsoft.TestPlatform.Common/Hosting/TestHostMetadata.cs#L14)):*
> ```Smalltalk
>     {
>         /// <summary>
>         /// Constructor for TestHostMetadata
> ```

Resharper generates a beautiful stylecop compliant summary header. Suggest to use it.

---

*[src/Microsoft.TestPlatform.Common/Hosting/TestHostProviderManager.cs, line 33 at r1](https://reviewable.io:443/reviews/microsoft/vstest/507#-KdYeno7DbLSlxW4zz0W:-KdYeno7DbLSlxW4zz0X:b-vxbi52) ([raw file](https://github.com/microsoft/vstest/blob/bb3fc2ab5070026cbe5067ee913 [...]

2017-02-27 02:02 UTC, codito requested changes
Suggested few changes.

2017-03-08 11:54 UTC, codito commented
@dotnet-bot test this please

2017-03-09 01:13 UTC, codito commented on src/Microsoft.TestPlatform.Common/ExtensionFramework/TestPluginDiscoverer.cs
> +                TestHosts = new Dictionary<string, TestHostPluginInformation>(StringComparer.OrdinalIgnoreCase)
We plan to rename TestHostPluginInformation to TestRuntimePluginInformation?

2017-03-09 01:14 UTC, codito commented on src/Microsoft.TestPlatform.Common/Hosting/TestRunTimeExtensionManager.cs
> +    internal class TestRunTimeExtensionManager : TestExtensionManager<ITestRunTimeProvider, ITestRunTimeCapabilities>
`TestRuntimeExtensionManager` since runtime is one word.

2017-03-09 01:15 UTC, codito commented on src/Microsoft.TestPlatform.Common/Hosting/TestRunTimeExtensionManager.cs
> +    internal class TestRunTimeExtensionManager : TestExtensionManager<ITestRunTimeProvider, ITestRunTimeCapabilities>
Please update other usages of RunTime.

2017-03-09 01:17 UTC, codito commented on src/Microsoft.TestPlatform.CrossPlatEngine/Hosting/DefaultTestHostManager.cs
> +        public CancellationTokenSource GetCancellationTokenSource()
This should be private.

2017-03-09 01:19 UTC, codito commented on src/Microsoft.TestPlatform.CrossPlatEngine/Hosting/DotnetTestHostManager.cs
> +        private Action<Process, string> ErrorReceivedCallback => ((process, data) =>
DRY violation. Can this be extracted out?

2017-03-09 01:23 UTC, codito approved these changes
Other suggestions we plan to take in next PR:
- Remove Host namespace
- Add HostExited event to ITestRuntimeProvider

2017-03-09 12:34 UTC, merged