Added API to provide mutiple regex patterns for enumerating files.
microsoft/vstest pull request #922
Opened 2017-07-11 06:59 UTC by harshjain2

Added API to provide mutiple regex patterns for enumerating files.
This should give perf benefit as Directory.EnumerageFiles is called only once and files names are matched using multiple regex patterns.

2017-07-11 07:43 UTC, codito commented on src/Microsoft.TestPlatform.Client/TestPlatform.cs
> +                    var extensionAssemblies = new List<string>(this.fileHelper.EnumerateFiles(adapterPath, patterns, SearchOption.AllDirectories));
Not sure if the responsibility to combine and create a regex should be with EnumerateFiles.

2017-07-11 07:44 UTC, codito commented on src/Microsoft.TestPlatform.Client/TestPlatform.cs
> +                    var patterns = new string[] { TestPlatformConstants.TestAdapterRegexPattern, TestPlatformConstants.TestLoggerRegexPattern, TestPlatformConstants.RunTimeRegexPattern, TestPlatformC
If all these patterns are known why not Regex.Compile it directly in this class. We will save some time during runtime?

2017-07-11 07:55 UTC, codito requested changes
Suggest few changes.

2017-07-12 10:09 UTC, AbhitejJohn commented
quick question: How much of a perf benefit did this net us? Just curious.

2017-07-12 12:31 UTC, codito commented on src/Microsoft.TestPlatform.Client/TestPlatform.cs
> +                    var regex = new Regex(string.Join("|", patterns), RegexOptions.Compiled | RegexOptions.IgnoreCase);
Can this regex be a constant?

2017-07-12 12:31 UTC, codito commented on src/Microsoft.TestPlatform.Client/TestPlatform.cs
> +                    var patterns = new string[] { TestPlatformConstants.TestAdapterRegexPattern, TestPlatformConstants.TestLoggerRegexPattern, TestPlatformConstants.RunTimeRegexPattern, TestPlatformC
nit: runtime is one word

2017-07-12 12:31 UTC, codito commented on src/Microsoft.TestPlatform.CrossPlatEngine/Client/ProxyExecutionManager.cs
> +                extensions.AddRange(TestPluginCache.Instance.PathToExtensions.Where(ext => TestExecutorExtensionManager.Regex.IsMatch(ext)));
Should these be different regular expression than the discovery one?

2017-07-12 12:31 UTC, codito commented on src/Microsoft.TestPlatform.Common/ExtensionFramework/DataCollectionExtensionManager.cs
> +        public static Regex Regex = new Regex(TestPlatformConstants.DataCollectorRegexPattern, RegexOptions.Compiled | RegexOptions.IgnoreCase);
nit: can be more specific name?

2017-07-12 12:31 UTC, codito commented on src/Microsoft.TestPlatform.Client/TestPlatform.cs
> +                    var patterns = new string[] { TestPlatformConstants.TestAdapterRegexPattern, TestPlatformConstants.TestLoggerRegexPattern, TestPlatformConstants.RunTimeRegexPattern, TestPlatformC
Most of the patterns are compatible with `string.EndsWith`. Do we know how does string comparison compare with regex? Is there any observable startup time impact in regex compiled?

2017-07-14 09:39 UTC, harshjain2 commented on src/Microsoft.TestPlatform.Client/TestPlatform.cs
> +                    var patterns = new string[] { TestPlatformConstants.TestAdapterRegexPattern, TestPlatformConstants.TestLoggerRegexPattern, TestPlatformConstants.RunTimeRegexPattern, TestPlatformC
On measuring perf, it is observed that `String.EndsWith` performs better than `Regex`, therefore switched to `String.EndsWith` approach.

2017-07-14 12:25 UTC, codito approved these changes

2017-07-14 13:28 UTC, merged