Added Level as prefix for loggers.
microsoft/vstest pull request #967
Opened 2017-08-01 11:32 UTC by harshjain2

Added Level as prefix for loggers.

2017-08-01 11:49 UTC, smadala commented on test/Microsoft.TestPlatform.CoreUtilities.UnitTests/Output/OutputExtensionsTests.cs
> +            this.mockOutput.Verify(o => o.WriteLine("Error: HelloError", OutputLevel.Error), Times.Once());
Can we use  `Resources.CommandLineError` here?

2017-08-02 10:21 UTC, harshjain2 commented
@dotnet-bot test this.

2017-08-02 10:21 UTC, harshjain2 commented
@dotnet-bot test this please.

2017-08-03 14:32 UTC, codito requested changes

2017-08-03 14:32 UTC, codito commented on src/Microsoft.TestPlatform.CoreUtilities/Output/OutputExtensions.cs
> +        internal static bool AppendPrefix;
I am not sure if an Extension methods unit should contain state or configuration.

2017-08-03 14:32 UTC, codito commented on src/vstest.console/Internal/ConsoleLogger.cs
> +                bool.TryParse(prefix, out OutputExtensions.AppendPrefix);
If this returns false, we don't need to log?

2017-08-03 14:32 UTC, codito commented on test/Microsoft.TestPlatform.CoreUtilities.UnitTests/Output/OutputExtensionsTests.cs
> +            OutputExtensions.AppendPrefix = true;
Do we need to validate other scenarios? Can it be a data driven test?

2017-08-03 14:33 UTC, codito commented on src/Microsoft.TestPlatform.CoreUtilities/Output/OutputExtensions.cs
> +        internal static bool AppendPrefix;
Not sure if an extension methods class should have state.

2017-08-10 07:00 UTC, smadala commented
Having prefix=true always makes finding warning and error messages easy, especially output is redirect to files in CI/CD scenarios. Currently user can identify the level of message by color of message in console which we loss once it redirect to file.

Update help for `vstest.console.exe` and `dotnet test`, update doc in vstest-docs.

2017-08-11 13:02 UTC, Faizan2304 approved these changes

2017-08-31 04:53 UTC, smadala approved these changes
Add doc in vstest-docs.

2017-08-31 04:58 UTC, merged